### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by dapsjj** [IDKiro/Attack-ImageNet#2]
When I run `simple_attack.py`.
There is an error:

> simple_attack.py 85 <module>
> model.cuda()
> 
> module.py 260 cuda
> return self._apply(lambda t: t.cuda(device))
> 
> module.py 187 _apply
> module._apply(fn)
> 
> module.py 187 _apply
> module._apply(fn)
> 
> module.py 187 _apply
> module._apply(fn)
> 
> module.py 193 _apply
> param.data = fn(param.data)
> 
> module.py 260 <lambda>
> return self._apply(lambda t: t.cuda(device))
> 
> __init__.py 161 _lazy_init
> _check_driver()
> 
> __init__.py 75 _check_driver
> raise AssertionError("Torch not compiled with CUDA enabled")
> 
> AssertionError:
> Torch not compiled with CUDA enabled

How to fix it?

**Comment by IDKiro** [comment]
google can help you, not me
