### ISSUE TITLE
Some error in "./utils/Resnet.py"

### ISSUE THREAD

**Issue by tuji-sjp** [IDKiro/Attack-ImageNet#3]
When I run your code, I get the following error:
**TypeError: einsum() takes 2 positional arguments but 3 were given**

    def forward(self, x):
        if self.embed:
            theta = self.conv_theta(x)
            phi = self.conv_phi(x)
        else:
            theta = x
            phi = x
        n_in, H, W = list(x.size())[1:]
        if n_in > H*W or self.softmax:
            f = torch.einsum('niab,nicd->nabcd', theta,phi)
            if self.softmax:
                shape = f.size()
                f = f.view(-1, shape[2]*shape[3], shape[2]*shape[3])
                f = f / math.sqrt(self.channel/2)
                f = nn.functional.softmax(f, dim=-1)
                f = f.view(shape)
            f = torch.einsum('nabcd,nicd->niab', f, x)
        else:
            f = torch.einsum('nihw,njhw->nij', phi, x)
            f = torch.einsum('nij,nihw->njhw', f, theta)
        if not self.softmax:
            f = f / (H*W)
            
        y = self.bn(self.conv(f))
        return x + y

Please help me solve this puzzle, thank you!

**Comment by IDKiro** [comment]
Maybe pytorch version mismatch.

**Comment by tuji-sjp** [comment]
Ok, I will change the version, thanks.
