### ISSUE TITLE
请问一下可迁移性是如何判断的呢？

### ISSUE THREAD

**Issue by tuji-sjp** [IDKiro/Attack-ImageNet#4]
请问您的代码生成的对抗样本的可迁移性是如何评估的呢？所攻击的黑盒模型是什么呢？

**Comment by IDKiro** [comment]
？这是比赛代码，当然是比赛的成绩评估可迁移性

**Comment by tuji-sjp** [comment]
我看了一下官方好像没有说明最后评估的是哪三个防御模型，是吗？
那如果是自己的实验，应该选择哪些模型进行评估呢？

**Comment by IDKiro** [comment]
就比赛前三名的结果来说，官方用的模型就是我用的模型，可能加了点其他操作或者finetune过。
线下评估可迁移性一般在vggnet、resnet上即可，这个可以查阅黑盒共计方法的实验部分。
