### ISSUE TITLE
RuntimeError: cuDNN error

### ISSUE THREAD

**Issue by Troye-van** [IDKiro/Attack-ImageNet#5]
When I run your code, I get this error:

**RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.**

The error occurs when I run line 83 "loss.backward()" in **attacker.py**, I don't know what's going on here.
Maybe you know how to solve it?

**Comment by IDKiro** [comment]
package version?
pytorch, cudatoolkit, cudnn, python ...
i think this kind of problem can be fix by search on google

**Comment by IDKiro** [comment]
i'd like to close it since you did not reply
