### ISSUE TITLE
请问pytorch的防御模型有fine-tune过吗？

### ISSUE THREAD

**Issue by shunchang-liu** [IDKiro/Attack-ImageNet#6]

**Comment by IDKiro** [comment]
没有，是直接转过来的。
fine-tune防御模型的开销有点太大了。

**Comment by IDKiro** [comment]
另外第二期的线上模型就算有fine-tune也就fine-tune了几轮，不清楚现在第六期的情况

**Comment by shunchang-liu** [comment]
> 另外第二期的线上模型就算有fine-tune也就fine-tune了几轮，不清楚现在第六期的情况

谢谢！用Adv_Denoise_Resnet152在clean上跑只有15准确率，不知道哪里出了问题。。。

**Comment by IDKiro** [comment]
归一化，颜色通道
这个输入通道我记得是BGR
