### ISSUE TITLE
Add input diversity (resize and padding).[3]Add input diversity (resize and padding).[3]

### ISSUE THREAD

**Issue by yjt9299** [IDKiro/Attack-ImageNet#7]
where is the implement...

**Comment by IDKiro** [comment]
In `attacker.py`
```
    def input_diversity(self, image, low=270, high=299):
        if random.random() > self.div_prob:
            return image
        rnd = random.randint(low, high)
        rescaled = F.interpolate(image, size=[rnd, rnd], mode='bilinear')
        h_rem = high - rnd
        w_rem = high - rnd
        pad_top = random.randint(0, h_rem)
        pad_bottom = h_rem - pad_top
        pad_left = random.randint(0, w_rem)
        pad_right = w_rem - pad_left
        padded = F.pad(rescaled, [pad_top, pad_bottom, pad_left, pad_right], 'constant', 0)
        return padded
```

**Comment by yjt9299** [comment]
> In `attacker.py`
> 
> ```
>     def input_diversity(self, image, low=270, high=299):
>         if random.random() > self.div_prob:
>             return image
>         rnd = random.randint(low, high)
>         rescaled = F.interpolate(image, size=[rnd, rnd], mode='bilinear')
>         h_rem = high - rnd
>         w_rem = high - rnd
>         pad_top = random.randint(0, h_rem)
>         pad_bottom = h_rem - pad_top
>         pad_left = random.randint(0, w_rem)
>         pad_right = w_rem - pad_left
>         padded = F.pad(rescaled, [pad_top, pad_bottom, pad_left, pad_right], 'constant', 0)
>         return padded
> ```

oh~  thank u very much
