### ISSUE TITLE
is_better = loss < best_loss

### ISSUE THREAD

**Issue by zengen226** [IDKiro/Attack-ImageNet#8]
`is_better = loss < best_loss;
best_loss[is_better] = loss[is_better];
best_delta[is_better] = delta.data[is_better]`
Would you please tell me the meaning of this code?The following error was reported while running:
“too many indices for tensor of dimension 0”

**Comment by IDKiro** [comment]
This is for updating best attacking loss.
Since the mini batch size is large than 1, so using [is_better] for indexing (only update the necessary parts).

PS:
It’s been a long time, I’m not sure.
