### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DetachedGYQ** [IDKiro/Attack-ImageNet#9]
请问为什么要给标签添加偏移量啊，是原始数据已经做过处理了吗，这个偏移量使我产生了类型的错误subscriptable，如果不予理会，会事得分降低吗。

**Comment by IDKiro** [comment]
好像是因为比赛的数据中标签0表示背景，总共有1001类，我为了和一些参考的代码对上，加了个偏移量，具体我也记不清了。
要保证模型输出类别编码（label顺序）和使用的数据一致才能保证结果。
